version: '3'
services:
  database:
    image: mariadb:10.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'cinemas'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user123'
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8083:80'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    depends_on:
      - database

  webserver:
    image: httpd:2.4
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./webserver:/var/www/html
    depends_on:
      - database

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/app
    depends_on:
      - webserver
    tty: true
    stdin_open: true
    ports:
      - '8081:80'
    expose:
      - '8081'