version: '3'
services:
  database:
    image: mariadb:10.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'cinemas'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user123'
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8083:80'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      UPLOAD_LIMIT: 300M
    depends_on:
      - database

  webserver:
    image: httpd:2
    ports:
      - '80:80'
    volumes:
      - ./webserver:/usr/local/apache2/htdocs
    depends_on:
      - database

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    volumes:
      - ./express:/app
    ports:
      - '8081:80'
    expose:
      - '8081'