version: '3'
services:
  database:
    image: mariadb:10.7
    ports:
      - '3307:3306'
    expose:
      - '3307'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'cinemas'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8083:80'
    environment:
      PMA_HOST: 'database'
      PMA_PORT: '3307'
      PMA_USER: 'test'
      PMA_PASSWORD: 'test'
    depends_on:
      - database

  webserver:
    image: httpd:2
    ports:
      - '80:80'
    volumes:
      - ./webserver:/var/www/html
    depends_on:
      - database

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/app
    depends_on:
      - webserver
    tty: true
    stdin_open: true
    ports:
      - '8081:80'
    expose:
      - '8081'